### ISSUE TITLE
~ ethereum-vanity-wallet -p ab -s cd is a directory

### ISSUE THREAD

**Issue by Maxyao1** [meehow/ethereum-vanity-wallet#1]
Help please, for the second day I can not understand why it does not work. I installed it in the folder ethereum-vanity-wallet-master, everything was successfully installed, all files are in place and ready to work, but after entering the command ~ ethereum-vanity-wallet -p ab -s cd nothing happens, only writes that this directory and everything. How do I run the script correctly?
![image](https://user-images.githubusercontent.com/82271891/168824499-5809b165-4e72-4c05-8319-cefc1af4ad2e.png)

**Comment by meehow** [comment]
You need to run a command `go install github.com/meehow/ethereum-vanity-wallet@latest`
